<?php

namespace Database\Seeders;

use App\Models\Menu; // Correct import
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->datas() as $key => $value) {
            $this->createMenu($value);
        }
    }

    private function createMenu($data, $parent_id = null)
    {
        $attributes = [
            'name' => $data['name'],
            'parent_id' => $parent_id,
        ];

        $values = [
            'icon' => $data['icon'],
            'route' => $data['route'],
            'description' => $data['description'],
            'sorting' => $data['sorting'],
            'permission_name' => $data['permission_name'],
            'status' => $data['status'],
            'deleted_at' => null,
        ];

        $menu = Menu::updateOrCreate($attributes, $values);

        if (isset($data['children']) && is_array($data['children'])) {
            foreach ($data['children'] as $child) {
                $this->createMenu($child, $menu->id);
            }
        }
    }

    private function datas()
    {
        return [
            [
                'name' => 'Dashboard',
                'icon' => 'dashboard',
                'route' => 'backend.dashboard',
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'dashboard',
                'status' => 'Active',
            ],
            // [
            //     'name' => 'Module Make',
            //     'icon' => 'slack',
            //     'route' => 'backend.moduleMaker',
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'module maker',
            //     'status' => 'Active',
            // ],
            [
                'name' => 'Billing',
                'icon' => 'billing',
                'route' => 'backend.billing.Page',
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'billing',
                'status' => 'Active',
            ],
            [
                'name' => 'Human Resource',
                'icon' => 'human',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'user-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Staff Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.admin.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'Admin-add',
                    //     'status' => 'Active',
                    // ],
                    [
                        'name' => 'Staff List',
                        'icon' => 'list',
                        'route' => 'backend.admin.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'admin-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Designation Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.designation.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'designation-add',
                    //     'status' => 'Active',
                    // ],
                    [
                        'name' => 'Designation List',
                        'icon' => 'list',
                        'route' => 'backend.designation.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'designation-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Specialist Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.specialist.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'specialist-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Specialist List',
                        'icon' => 'list',
                        'route' => 'backend.specialist.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'specialist-list',
                        'status' => 'Active',
                    ],
                ],
            ],
            // [
            //     'name' => 'Permission Manage',
            //     'icon' => 'unlock',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'permission-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Permission Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.permission.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'permission-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Permission List',
            //             'icon' => 'list',
            //             'route' => 'backend.permission.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'permission-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],
            [
                'name' => 'Role Management',
                'icon' => 'role-management',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'role-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Role Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.role.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'role-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Role List',
                        'icon' => 'list',
                        'route' => 'backend.role.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'role-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            [
                'name' => 'Patient',
                'icon' => 'user',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'patient-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Patient Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.patient.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'patient-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Patient List',
                        'icon' => 'list',
                        'route' => 'backend.patient.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'patient-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            // [
            //     'name' => 'Billing',
            //     'icon' => 'file-text',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'billing-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Billing Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.billing.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'billing-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Billing List',
            //             'icon' => 'list',
            //             'route' => 'backend.billing.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'billing-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],

            [
                'name' => 'Appoinment',
                'icon' => 'appointment',
                'route' => 'backend.appoinment.index',
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'appoinment-list',
                'status' => 'Active',
            ],

            // [
            //     'name' => 'Appoinment',
            //     'icon' => 'appointment',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'appoinment-management',
            //     'status' => 'Active',
            //     'children' => [
            //         // [
            //         //     'name' => 'Appoinment Add',
            //         //     'icon' => 'plus-circle',
            //         //     'route' => 'backend.appoinment.create',
            //         //     'description' => null,
            //         //     'sorting' => 1,
            //         //     'permission_name' => 'appoinment-add',
            //         //     'status' => 'Active',
            //         // ],
            //         [
            //             'name' => 'Appoinment List',
            //             'icon' => 'list',
            //             'route' => 'backend.appoinment.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'appoinment-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],

            [
                'name' => 'OPD - Out Patient',
                'icon' => 'stethoscope',
                'route' => 'backend.opdpatient.index',
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'opd-patient-list',
                'status' => 'Active',
            ],

            // [
            //     'name' => 'OPD - Out Patient',
            //     'icon' => 'stethoscope',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'opdpatient-management',
            //     'status' => 'Active',
            //     'children' => [
            //         // [
            //         //     'name' => 'OpdPatient Add',
            //         //     'icon' => 'plus-circle',
            //         //     'route' => 'backend.opdpatient.create',
            //         //     'description' => null,
            //         //     'sorting' => 1,
            //         //     'permission_name' => 'opdpatient-add',
            //         //     'status' => 'Active',
            //         // ],
            //         [
            //             'name' => 'OpdPatient List',
            //             'icon' => 'list',
            //             'route' => 'backend.opdpatient.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'opd-patient-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            [
                'name' => 'IPD - In Patient',
                'icon' => 'ipd',
                'route' => 'backend.ipdpatient.index',
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'ipd-patient-list',
                'status' => 'Active',
            ],

            // [
            //     'name' => 'IPD - In Patient',
            //     'icon' => 'ipd',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'ipdpatient-management',
            //     'status' => 'Active',
            //     'children' => [
            //         // [
            //         //     'name' => 'IpdPatient Add',
            //         //     'icon' => 'plus-circle',
            //         //     'route' => 'backend.ipdpatient.create',
            //         //     'description' => null,
            //         //     'sorting' => 1,
            //         //     'permission_name' => 'ipdpatient-add',
            //         //     'status' => 'Active',
            //         // ],
            //         [
            //             'name' => 'IpdPatient List',
            //             'icon' => 'list',
            //             'route' => 'backend.ipdpatient.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'ipd-patient-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Pharmacy',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'pharmacy-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Pharmacy Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.pharmacy.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'pharmacy-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Pharmacy List',
            //             'icon' => 'list',
            //             'route' => 'backend.pharmacy.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'pharmacy-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            [
                'name' => 'Pathology',
                'icon' => 'flask',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'pathology-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Pathology Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.pathology.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'pathology-add',
                    //     'status' => 'Active',
                    // ],
                    [
                        'name' => 'Pathology List',
                        'icon' => 'list',
                        'route' => 'backend.pathology.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'pathology-list',
                        'status' => 'Active',
                    ]
                ],
            ],


            [
                'name' => 'Radiology',
                'icon' => 'microscope',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'radiology-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Radiology Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.radiology.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'radiology-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Radiology List',
                        'icon' => 'list',
                        'route' => 'backend.radiology.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'radiology-list',
                        'status' => 'Active',
                    ],
                ],
            ],


            // [
            //     'name' => 'Blood Bank',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'bloodbank-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'BloodBank Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.bloodbank.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'bloodbank-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'BloodBank List',
            //             'icon' => 'list',
            //             'route' => 'backend.bloodbank.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'bloodbank-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Ambulance',
            //     'icon' => 'truck',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'ambulance-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Ambulance Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.ambulance.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'ambulance-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Ambulance List',
            //             'icon' => 'list',
            //             'route' => 'backend.ambulance.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'ambulance-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Front Office',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'frontoffice-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'FrontOffice Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.frontoffice.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'frontoffice-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'FrontOffice List',
            //             'icon' => 'list',
            //             'route' => 'backend.frontoffice.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'frontoffice-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Birth & Death Record',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'birthdeathrecord-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'BirthDeathRecord Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.birthdeathrecord.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'birthdeathrecord-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'BirthDeathRecord List',
            //             'icon' => 'list',
            //             'route' => 'backend.birthdeathrecord.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'birthdeathrecord-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Duty Roaster',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'dutyroaster-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'DutyRoaster Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.dutyroaster.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'dutyroaster-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'DutyRoaster List',
            //             'icon' => 'list',
            //             'route' => 'backend.dutyroaster.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'dutyroaster-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Annual Calendar',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'annualcalendar-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'AnnualCalendar Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.annualcalendar.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'annualcalendar-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'AnnualCalendar List',
            //             'icon' => 'list',
            //             'route' => 'backend.annualcalendar.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'annualcalendar-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            [
                'name' => 'Referral',
                'icon' => 'referral',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'referral-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Referral Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.referral.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'referral-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Referral List',
                        'icon' => 'list',
                        'route' => 'backend.referral.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'referral-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Referral Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.referralperson.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'referralperson-add',
                    //     'status' => 'Active',
                    // ],
                    [
                        'name' => 'Referral Person List',
                        'icon' => 'list',
                        'route' => 'backend.referralperson.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'referral-person-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'ReferralCategory Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.referralcategory.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'referralcategory-add',
                    //     'status' => 'Active',
                    // ],
                    [
                        'name' => 'Referral Category',
                        'icon' => 'list',
                        'route' => 'backend.referralcategory.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'referral-category-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            [
                'name' => 'TPA Management',
                'icon' => 'umbrella',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'tpa-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Tpa Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.tpa.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'tpa-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Tpa List',
                        'icon' => 'list',
                        'route' => 'backend.tpa.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'tpa-list',
                        'status' => 'Active',
                    ],
                ],
            ],


            // [
            //     'name' => 'Inventory',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'inventory-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Inventory Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.inventory.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'inventory-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Inventory List',
            //             'icon' => 'list',
            //             'route' => 'backend.inventory.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'inventory-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Certificate',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'certificate-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Certificate Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.certificate.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'certificate-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Certificate List',
            //             'icon' => 'list',
            //             'route' => 'backend.certificate.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'certificate-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Reports',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'reports-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Reports Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.reports.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'reports-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Reports List',
            //             'icon' => 'list',
            //             'route' => 'backend.reports.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'reports-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            // [
            //     'name' => 'Setup',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'setup-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'Setup Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.setup.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'setup-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'Setup List',
            //             'icon' => 'list',
            //             'route' => 'backend.setup.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'setup-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            [
                'name' => 'BloodIssue Manage',
                'icon' => 'blood-bank',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'blood-issue-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'BloodIssue Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.bloodissue.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'bloodissue-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'BloodIssue List',
                        'icon' => 'list',
                        'route' => 'backend.bloodissue.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'blood-issue-list',
                        'status' => 'Active',
                    ],
                ],
            ],


            [
                'name' => 'BloodComponentIssue Manage',
                'icon' => 'bloodComponent',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'blood-componentissue-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'BloodComponentIssue Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.bloodcomponentissue.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'bloodcomponentissue-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'BloodComponentIssue List',
                        'icon' => 'list',
                        'route' => 'backend.bloodcomponentissue.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'blood-component-issue-list',
                        'status' => 'Active',
                    ],
                ],
            ],


            [
                'name' => 'Bed Manage',
                'icon' => 'bed',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'bed-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Bed Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.bed.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'bed-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Bed List',
                        'icon' => 'list',
                        'route' => 'backend.bed.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'bed-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Bed Type Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.bedtype.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'bedtype-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Bed Type List',
                        'icon' => 'list',
                        'route' => 'backend.bedtype.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'bed-type-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'BedGroup Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.bedgroup.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'bedgroup-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'BedGroup List',
                        'icon' => 'list',
                        'route' => 'backend.bedgroup.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'bed-group-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Floor Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.floor.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'floor-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Floor List',
                        'icon' => 'list',
                        'route' => 'backend.floor.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'floor-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            [
                'name' => 'Hospital Charge',
                'icon' => 'dollar-sign',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'hospital-charge',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Charge Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.hospitalcharge.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'charge-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Charge List',
                        'icon' => 'list',
                        'route' => 'backend.hospitalcharge.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'charge-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Charge Category Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.chargecategory.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'chargecategory-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Charge Category List',
                        'icon' => 'list',
                        'route' => 'backend.chargecategory.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'charge-category-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Charge Type Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.chargetype.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'chargetype-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Charge Type List',
                        'icon' => 'list',
                        'route' => 'backend.chargetype.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'charge-type-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Tax Category Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.chargetaxcategory.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'chargetaxcategory-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Tax Category List',
                        'icon' => 'list',
                        'route' => 'backend.chargetaxcategory.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'charge-tax-category-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Charge Unit Type Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.chargeunittype.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'chargeunittype-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Charge Unit Type List',
                        'icon' => 'list',
                        'route' => 'backend.chargeunittype.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'charge-unit-type-list',
                        'status' => 'Active',
                    ]
                ],
            ],

            [
                'name' => 'Hospital Test',
                'icon' => 'layers',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'hospital-test',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Test Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.testpathology.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'test-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Test List',
                        'icon' => 'list',
                        'route' => 'backend.testpathology.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'test-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Test Category Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.pathologycategory.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'test-category-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Test Category List',
                        'icon' => 'list',
                        'route' => 'backend.pathologycategory.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'test-category-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Test Unit Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.pathologyunit.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'test-unit-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Test Unit List',
                        'icon' => 'list',
                        'route' => 'backend.pathologyunit.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'test-unit-list',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Test Parameter Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.parameterofpathology.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'test-parameter-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Test Parameter List',
                        'icon' => 'list',
                        'route' => 'backend.parameterofpathology.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'test-parameter-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            [
                'name' => 'Inventory',
                'icon' => 'inventory',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'inventory-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Inventory Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.inventory.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'inventory-add',
                    //     'status' => 'Active',
                    // ],
                    // [
                    //     'name' => 'Inventory List',
                    //     'icon' => 'list',
                    //     'route' => 'backend.inventory.index',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'inventory-list',
                    //     'status' => 'Active',
                    // ],

                    [
                        'name' => 'Medicine Inventory List',
                        'icon' => 'list',
                        'route' => 'backend.medicineinventory.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'medicine-inventory-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            [
                'name' => 'Pharmacy Management',
                'icon' => 'pharmacy',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'pharmacy-management',
                'status' => 'Active',
                'children' => [
                    [
                        'name' => 'Medicine Inventory',
                        'icon' => 'list',
                        'route' => 'backend.medicineinventory.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'medicine-inventory-list',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'Add Medicine',
                        'icon' => 'plus-circle',
                        'route' => 'backend.medicineinventory.create',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'medicine-inventory-add',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'Supplier Payment History',
                        'icon' => 'list',
                        'route' => 'backend.pharmacy.supplier.payment',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'supplier-payment-list',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'Product Return',
                        'icon' => 'list',
                        'route' => 'backend.pharmacy.return.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'product-return-list',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'Stock Report',
                        'icon' => 'list',
                        'route' => 'backend.pharmacy.stock.report',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'stock-report-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            [
                'name' => 'InvoiceDesign Manage',
                'icon' => 'invoice-design',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'invoicedesign-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'InvoiceDesign Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.invoicedesign.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'invoicedesign-add',
                    //     'status' => 'Active',
                    // ],

                ],
            ],

            [
                'name' => 'Reports',
                'icon' => 'reports',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'report-management',
                'status' => 'Active',
                'children' => [
                    [
                        'name' => 'Report List',
                        'icon' => 'list',
                        'route' => 'backend.report.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'report-list',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'Finance Report',
                        'icon' => 'list',
                        'route' => 'backend.finance-report.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'finance-report',
                        'status' => 'Active',
                    ],
                ],
            ],

            [
                'name' => 'Settings',
                'icon' => 'settings',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'settings-management',
                'status' => 'Active',
                'children' => [
                    [
                        'name' => 'InvoiceDesign List',
                        'icon' => 'list',
                        'route' => 'backend.invoicedesign.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'invoice-design-list',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'BillingDoctor List',
                        'icon' => 'list',
                        'route' => 'backend.billingdoctor.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'billing-doctor-list',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'Websetting',
                        'icon' => 'list',
                        'route' => 'backend.websetting.create',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'websetting-add',
                        'status' => 'Active',
                    ],
                    // [
                    //     'name' => 'Charge Import',
                    //     'icon' => 'list',
                    //     'route' => 'backend.charges.import.form',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'charge-import-form',
                    //     'status' => 'Active',
                    // ],
                ],
            ],


            // [
            //     'name' => 'PharmacyBill Manage',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'pharmacybill-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'PharmacyBill Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.pharmacybill.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'pharmacybill-add',
            //             'status' => 'Active',
            //         ],
            //         [
            //             'name' => 'PharmacyBill List',
            //             'icon' => 'list',
            //             'route' => 'backend.pharmacybill.index',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'pharmacybill-list',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],

            [
                "name" => "Payroll",
                "icon" => "payroll",
                "route" => null,
                "description" => null,
                "sorting" => 11,
                "permission_name" => "payroll-management",
                "status" => "Active",
                "children" => [
                    // [
                    //     "name" => "Staff Attendance",
                    //     "icon" => "plus-circle",
                    //     "route" => "backend.staffattendance.create",
                    //     "description" => null,
                    //     "sorting" => 1,
                    //     "permission_name" => "staff-attendance-add",
                    //     "status" => "Active",
                    // ],
                    [
                        "name" => "Attendance List",
                        "icon" => "list",
                        "route" => "backend.staffattendance.index",
                        "description" => null,
                        "sorting" => 2,
                        "permission_name" => "staff-attendance-list",
                        "status" => "Active",
                    ],
                    // [
                    //     "name" => "Staff Attendance Report",
                    //     "icon" => "list",
                    //     "route" => "backend.staffattendance.report",
                    //     "description" => null,
                    //     "sorting" => 3,
                    //     "permission_name" => "staff-attendance-report-list",
                    //     "status" => "Active",
                    // ],
                    // [
                    //     "name" => "Leave Type Create",
                    //     "icon" => "plus-circle",
                    //     "route" => "backend.Leavetype.create",
                    //     "description" => null,
                    //     "sorting" => 4,
                    //     "permission_name" => "leave-type-add",
                    //     "status" => "Active",
                    // ],
                    [
                        "name" => "Leave Type List",
                        "icon" => "list",
                        "route" => "backend.Leavetype.index",
                        "description" => null,
                        "sorting" => 5,
                        "permission_name" => "leave-type-list",
                        "status" => "Active",
                    ],
                    // [
                    //     "name" => "Define Leave Create",
                    //     "icon" => "plus-circle",
                    //     "route" => "backend.defineleave.create",
                    //     "description" => null,
                    //     "sorting" => 6,
                    //     "permission_name" => "leave-add",
                    //     "status" => "Active",
                    // ],
                    [
                        "name" => "Define Leave List",
                        "icon" => "list",
                        "route" => "backend.defineleave.index",
                        "description" => null,
                        "sorting" => 7,
                        "permission_name" => "define-leave-list",
                        "status" => "Active",
                    ],
                    // [
                    //     "name" => "Apply Leave",
                    //     "icon" => "plus-circle",
                    //     "route" => "backend.applyleave.create",
                    //     "description" => null,
                    //     "sorting" => 8,
                    //     "permission_name" => "apply-leave-add",
                    //     "status" => "Active",
                    // },
                    [
                        "name" => "Apply Leave List",
                        "icon" => "list",
                        "route" => "backend.applyleave.index",
                        "description" => null,
                        "sorting" => 9,
                        "permission_name" => "apply-leave-list",
                        "status" => "Active",
                    ],
                    // [
                    //     "name" => "Pending Leave Request",
                    //     "icon" => "list",
                    //     "route" => "backend.pending.request",
                    //     "description" => null,
                    //     "sorting" => 11,
                    //     "permission_name" => "pending-leave-list",
                    //     "status" => "Active",
                    // },
                    // [
                    //     "name" => "Approve Leave Request",
                    //     "icon" => "list",
                    //     "route" => "backend.approval.request",
                    //     "description" => null,
                    //     "sorting" => 10,
                    //     "permission_name" => "approve-leave-request",
                    //     "status" => "Active",
                    // },
                    [
                        "name" => "All Leave List",
                        "icon" => "list",
                        "route" => "backend.apply.list",
                        "description" => null,
                        "sorting" => 12,
                        "permission_name" => "applied-leave-list",
                        "status" => "Active",
                    ],
                ],
            ],


            // [
            //     'name' => 'ExpenseHead Manage',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'expensehead-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'ExpenseHead Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.expensehead.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'expensehead-add',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            [
                'name' => 'Expense Manage',
                'icon' => 'layers',
                'route' => null,
                'description' => null,
                'sorting' => 1,
                'permission_name' => 'expense-management',
                'status' => 'Active',
                'children' => [
                    // [
                    //     'name' => 'Expense Add',
                    //     'icon' => 'plus-circle',
                    //     'route' => 'backend.expense.create',
                    //     'description' => null,
                    //     'sorting' => 1,
                    //     'permission_name' => 'expense-add',
                    //     'status' => 'Active',
                    // },
                    [
                        'name' => 'Expense List',
                        'icon' => 'list',
                        'route' => 'backend.expense.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'expense-list',
                        'status' => 'Active',
                    ],
                    [
                        'name' => 'ExpenseHead List',
                        'icon' => 'list',
                        'route' => 'backend.expensehead.index',
                        'description' => null,
                        'sorting' => 1,
                        'permission_name' => 'expensehead-list',
                        'status' => 'Active',
                    ],
                ],
            ],

            // [
            //     'name' => 'BillingDoctor Manage',
            //     'icon' => 'layers',
            //     'route' => null,
            //     'description' => null,
            //     'sorting' => 1,
            //     'permission_name' => 'billingdoctor-management',
            //     'status' => 'Active',
            //     'children' => [
            //         [
            //             'name' => 'BillingDoctor Add',
            //             'icon' => 'plus-circle',
            //             'route' => 'backend.billingdoctor.create',
            //             'description' => null,
            //             'sorting' => 1,
            //             'permission_name' => 'billingdoctor-add',
            //             'status' => 'Active',
            //         ],
            //     ],
            // ],


            //don't remove this comment from menu seeder
        ];
    }
}
