@php
    $ipdFooterHtml = '<div class="hr"></div><table class="plain"><tr><td class="small muted">Generated by system | ' . e($vm['hospital']['name'] ?? '') . '</td><td class="small text-right muted">' . e($vm['invoice']['currency'] ?? '') . '</td></tr></table>';
@endphp

@include('prints.partials._footer', ['footer_content' => $ipdFooterHtml])
