<div class="footer">
    <div class="hr"></div>
    <table class="plain">
        <tr>
            <td class="small muted">
                Generated by system | {{ $vm['hospital']['name'] }}
            </td>
            <td class="small text-right muted">
                {{ $vm['invoice']['currency'] ?? '' }}
            </td>
        </tr>
    </table>
</div>
